openapi: 3.0.3
info:
  title: Kidney Stone Prediction API - Python REST API
  description: >-
    Kidney Stone Prediction API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:5000
tags:
  - name: prediction
    description: ML prediction
paths:
  /predict:
    summary: Predict Kidney Stone.
    get:
      summary: Predict Kidney Stone.
      operationId: PredictKidneyStone
      tags:
        - prediction
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Key"
                
  /healthz:
    summary: Healthcheck endpoint
    get:
      summary: Healthcheck
      operationId: Healthcheck
      responses:
        "200":
          description: Healthy response

components:
  schemas:
    Key:
      type: object
      properties:
        id:
          type: string
          example: "my-id"